#!/usr/bin/env sh

sketchybar --bar position=bottom color=0xFF000000

sketchybar -m --add event window_focus \
              --add event title_change

sketchybar -m --add event title_change

sketchybar -m --add item title left \
              --set title script="$HOME/.config/sketchybar/plugins/window_title.py" \
              --subscribe title title_change space_change front_app_switched window_focus



############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
